Repository cmu-crafting-software/in-class-2024, pull requests merged in 2024-02, with the labels that each got.

#14 Kitty's Pull Request
  feb-14-pandas/Kitty'sSolution.ipynb
  feb-14-pandas/exercises.md
  feb-14-pandas/result.csv
  feb-18-jupyter/world_guesser.ipynb
  feb-28-collab/README-kpierrel.md
  jan-24-files/PresidentSolution_Kitty.py
  jan-24-files/presidents.json
  jan-29-paths/Kitty'sSolution.ipynb
  jan-29-paths/presidents.json
Labels: good first issue, help wanted

#12 creating a pull request
  feb-14-pandas/exercises.md
  feb-14-pandas/in-class.py
  feb-18-jupyter/clean_worldle_player.ipynb
  feb-28-collab/README-zihengze.md
  feb-7-testing/wordle_parts.py
  feb-7-testing/wordle_parts_test.py
  jan-24-files/solution.py
  jan-29-paths/solution1-29.py
  jan-29-paths/step51-29.py
  jan-29-paths/step6.py
  recitation-1-26.py
Labels: documentation, help wanted

#13 Kferner pull request to add README-kferner.md
  feb-12-debugging/find_the_bug.py
  feb-14-pandas/solution.md
  feb-14-pandas/solution.py
  feb-28-collab/README-kferner.md
Labels: documentation

#16 Copy readme_Seonghaj
  feb-28-collab/README-<seonghaj>.md
  jan-24-files/presidents.csv
  jan-24-files/solution.py
  jan-24-files/workedExample.py
  jan-29-paths/presidents.json
  jan-29-paths/step3FromJan24JoshSolution.py
  jan-29-paths/workedExample.py
Labels: documentation

#15 Ddesprad inclass
  feb-14-pandas/dataanalysis.py
Labels: bug, help wanted
